### ISSUE TITLE
Crear un Design System desde 0

### ISSUE THREAD

**Issue by sergioalvz** [asturiashacking/projects#9]
# Crear un Design System desde 0

## Descripción

Actualmente los sistemas de diseño (aka design system en inglés) son una práctica muy habitual. Su función, por lo general, es diseñar una serie de piezas que se puedan re-utilizar después a lo largo de toda la suite de productos digitales de una empresa o marca. Algunos de los más conocidos son:

- [Polaris de Shopify](https://polaris.shopify.com/)
- [Nachos de Trello](https://design.trello.com/)
- [Material de Google](https://material.io/design/introduction/#principles)
- [Atlassian](https://atlassian.design/guidelines/product/overview)
- [Y otros muchos más...](https://www.designerlynx.co/design-systems)

Podríamos utilizar esta idea para introducirnos a tecnologías de front-end como React o Vue y diseñar algo que nos sea gracioso como un Design System asturiano con componentes como `<Botonin />` 😄 

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/projects/blob/master/TERMS.md

**Comment by m1guelpf** [comment]
Como idea, podríamos usar una framework como [Tailwind CSS](https://tailwindcss.com)

**Comment by sergioalvz** [comment]
Thanks @m1guelpf ! Yo iría sin framework, pero es sólo mi opinión 😋

**Comment by sergioalvz** [comment]
Para la librería de componentes, se me apetecería probar [Stencil](https://stenciljs.com/) que además se integraría muy bien después con proyectos React, Vue, Angular, etc.
